# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
blank_issues_enabled: true
contact_links:
  - name: General questions
    url: https://github.com/broetec/kubesure/discussions
    about: Use kubesure Discussions for questions that are not a bug report or feature request. Other Broetec projects may add their own Discussions over time.
